language: python
python:
    - 2.7
    - 3.6
#   - "nightly"  # currently points to 3.7-dev
install:
    - pip install -r requirements.txt
    - pip install flake8
before_script:
    flake8 . --count --max-line-length=88 --statistics --exit-zero
script:
    - ls
    - chmod +x *.py
    #- ./get_wsk_auth.py  # would do a webserver.open()
    - ./hello.py          # make sure example is still valid
    #- ./openwhisk.py     # self test will fail without a wsk_auth
    - python test_data_types.py
    - python test_logger.py
    - python test_url_generator.py
notifications:
    on_success: change
    on_failure: always
